version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: royalis_local
      MYSQL_ROOT_PASSWORD: azerty
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
        - db
    environment:
        MYSQL_ROOT_PASSWORD: azerty
        PMA_HOST: db
    ports:
        - 8001:80
    networks:
      - backend

  nodejs:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: docker/nodejs/Dockerfile
    restart: unless-stopped
    ports:
      - 8086:8080
    networks:
      - backend
      - frontend

  reactjs:
    depends_on:
      - nodejs
    build:
      context: .
      dockerfile: docker/reactjs/Dockerfile
      target: client_nginx
    ports:
      - 8888:80
    networks:
      - frontend

volumes:
  db:
  
networks:
  backend:
  frontend:
