version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: royalis_local
      MYSQL_ROOT_PASSWORD: azerty
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
        - mysqldb
    environment:
        MYSQL_ROOT_PASSWORD: azerty
        PMA_HOST: mysqldb
    ports:
        - 8001:80

  nodejs:
    depends_on:
      - mysqldb
    build: 
      context: .
      dockerfile: docker/nodejs/Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080

  reactjs:
    depends_on:
      - nodejs
    build:
      context: .
      dockerfile: docker/reactjs/Dockerfile
      target: client_nginx
    ports:
      - 8086:80

  mailhog:
    image: "mailhog/mailhog"
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db: