const endPoints = {
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  REFRESH_TOKEN: "/auth/refresh-token",
  FORGOT_PASSWORD: "/auth/forgot-password",
  REST_PASSWORD: "/auth/rest-password",
  CONFIRM_EMAIL: "/auth/confirm-email",
  PROFILE: "/auth/profile",
  DELETE_ACCOUNT : "/auth/delete-account",
  PLI : "/pli",
  PLI_NEW : "/pli/new",
  PLI_TIME : "/pli/time",
  PLIS : "/pli/list",
  PLI_SONDAGE_VOTE : "/pli/sondage/vote",
  PLI_SONDAGE_NOTE_VOTE : "/pli/sondage/not-vote",
  USER_SUBSCRIVBE : "/user/subscribe",
  USER_UNSUBSCRIVBE : "/user/unsubscribe",
  USER_SUBSCRICERS : "/user/subscribers/list", 
  USER_SUBSCRIPTIONS : "/user/subscriptions/list", 
  USER_SEARCH_LIST : "/user/search/list", 
  NOTIFICATION_NEW : "/notification/new",
  NOTIFICATION_LIST : "/notification/list", 
  NOTIFICATION_SEEN : "/notification/seen", 
  NOTIFICATION_SEEN_SUBSCRIPTIONS : "/notification/seen/subscriptions", 
  COMMENT_NEW : "/comment/new",
};
export default endPoints;
